name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2 and restart Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          script: |
            echo "=== Starting deployment ==="
            echo "Current user: $(whoami)"
            echo "Repository: ${{ github.repository }}"
            
            # Extract repo name from GitHub context
            REPO_NAME="${{ github.event.repository.name }}"
            echo "Deploying addon: $REPO_NAME"
            
            # Navigate to project directory (where docker-compose.yml is)
            echo "=== Navigating to project directory ==="
            cd /home/ubuntu/OdooInclue || { echo "Failed to navigate to OdooInclue directory"; exit 1; }
            echo "Project directory: $(pwd)"
            
            # Navigate to the specific addon directory for git operations
            echo "=== Navigating to addon directory: addons/$REPO_NAME ==="
            cd "addons/$REPO_NAME" || { echo "Failed to navigate to addon directory addons/$REPO_NAME"; exit 1; }
            echo "Addon directory: $(pwd)"
            
            # Check current git status
            echo "=== Current git status ==="
            git status
            git log --oneline -3
            
            # Set the correct SSH remote URL dynamically
            echo "=== Setting up git remote ==="
            EXPECTED_REMOTE="git@github.com:${{ github.repository }}.git"
            CURRENT_REMOTE=$(git remote get-url origin)
            
            if [ "$CURRENT_REMOTE" != "$EXPECTED_REMOTE" ]; then
              echo "Updating remote from $CURRENT_REMOTE to $EXPECTED_REMOTE"
              git remote set-url origin "$EXPECTED_REMOTE"
            fi
            echo "Git remote: $(git remote get-url origin)"
            
            # Force pull latest changes to avoid conflicts
            echo "=== Pulling latest changes from main branch ==="
            git fetch origin
            echo "Before reset: $(git log --oneline -1)"
            git reset --hard origin/main
            echo "After reset: $(git log --oneline -1)"
            
            # Show what files we have now in the addon directory
            echo "=== Files in addon directory (current location) ==="
            ls -la
            echo "=== Checking for common files ==="
            [ -f "__manifest__.py" ] && echo "✅ __manifest__.py found" || echo "❌ __manifest__.py missing"
            [ -f "test.txt" ] && echo "✅ test.txt content: $(cat test.txt)" || echo "ℹ️ test.txt not found"
            
            # Restart Docker containers directly by name
            echo "=== Restarting Docker containers ==="
            docker restart odooinclue-web-1
            echo "Web container restarted for addon: $REPO_NAME"
            
            # Check container status
            echo "=== Container status ==="
            docker ps --filter "name=odooinclue" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            
            echo "=== Deployment completed successfully for $REPO_NAME ==="